import React from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-between p-24">
      <Head>
        <title>AnalisisDatos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-col items-center justify-center space-y-20">
        {/* Hero moderno */}
        <div className="bg-white p-10 rounded-lg shadow-md max-w-3xl w-full text-center">
          <h1 className="text-4xl font-bold">Bienvenido a AnalisisDatos</h1>
          <p className="text-xl">Tu centro de análisis de datos</p>
        </div>

        {/* Barra superior */}
        <nav className="bg-gray-800 p-4 w-full">
          <ul className="flex justify-between items-center text-white">
            <li>Inicio</li>
            <li>Módulos</li>
            <li>Estadísticas</li>
            <li>Ayuda</li>
          </ul>
        </nav>

        {/* Buscador */}
        <div className="bg-gray-100 p-4 w-full max-w-3xl">
          <input type="text" placeholder="Buscar módulo..." className="w-full px-4 py-2 rounded-lg border border-gray-300 focus:outline-none focus:border-blue-500" />
        </div>

        {/* Sidebar */}
        <aside className="bg-white p-4 w-1/4 max-w-sm">
          <h2>Categorías</h2>
          <ul>
            <li>Category 1</li>
            <li>Category 2</li>
            <li>Category 3</li>
          </ul>
        </aside>

        {/* Tarjetas animadas */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 w-full max-w-3xl">
          <div className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
            <h3>Nombre del Módulo</h3>
            <p>Descripción del módulo.</p>
          </div>
          {/* Repite la estructura de tarjeta para otros módulos */}
        </div>

        {/* Accesos rápidos */}
        <div className="flex justify-center space-x-4 w-full max-w-3xl">
          <button className="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">Acceso Rápido 1</button>
          <button className="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">Acceso Rápido 2</button>
        </div>

        {/* Últimos módulos agregados */}
        <h2>Últimos Módulos Agregados</h2>
        <ul className="flex flex-col space-y-4">
          <li>Módulo 1</li>
          <li>Módulo 2</li>
          {/* Repite la estructura de lista para otros módulos */}
        </ul>

        {/* Estadísticas */}
        <div className="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
          <h3>Estadísticas Generales</h3>
          <p>Datos importantes del sistema.</p>
        </div>
      </main>

      {/* Tema claro/oscuro */}
      <button className="bg-gray-800 text-white px-4 py-2 rounded-lg hover:bg-gray-700">Cambiar Tema</button>
    </div>
  );
}
